### ISSUE TITLE
case sensitivity

### ISSUE THREAD

**Issue by richmarr** [dsferruzza/simpleSqlParser#14]
Hi,

Just testing out this module for unit testing any customer-written parts of our data layer. It looks like a great module, thanks for sharing. We bumped into a snag, which is that it seems to be case-sensitive in places.

For example, trying to do a simple join as below causes the error beneath:

```
select * from foo inner join bar on foo.id = bar.foo_id
```

Output:

```
TypeError: Cannot read property '0' of undefined
    at CondLexer.readNextChar (/Users/richardmarr/Projects/riskpenguin/lib/node_modules/simple-sql-parser/simpleSqlParser.js:368:34)
    at new CondLexer (/Users/richardmarr/Projects/riskpenguin/lib/node_modules/simple-sql-parser/simpleSqlParser.js:360:8)
    at new CondParser (/Users/richardmarr/Projects/riskpenguin/lib/node_modules/simple-sql-parser/simpleSqlParser.js:481:16)
    at Function.CondParser.parse (/Users/richardmarr/Projects/riskpenguin/lib/node_modules/simple-sql-parser/simpleSqlParser.js:567:10)
    at /Users/richardmarr/Projects/riskpenguin/lib/node_modules/simple-sql-parser/simpleSqlParser.js:340:47
    at Array.forEach (native)
    at Object.exports.sql2ast (/Users/richardmarr/Projects/riskpenguin/lib/node_modules/simple-sql-parser/simpleSqlParser.js:339:20)
    at Object.<anonymous> (/Users/richardmarr/Projects/riskpenguin/lib/test/parse.test.js:19:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at /Users/richardmarr/Projects/riskpenguin/lib/node_modules/mocha/lib/mocha.js:152:27
    at Array.forEach (native)
    at Mocha.loadFiles (/Users/richardmarr/Projects/riskpenguin/lib/node_modules/mocha/lib/mocha.js:149:14)
    at Mocha.run (/Users/richardmarr/Projects/riskpenguin/lib/node_modules/mocha/lib/mocha.js:306:31)
    at Object.<anonymous> (/Users/richardmarr/Projects/riskpenguin/lib/node_modules/mocha/bin/_mocha:348:7)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
```

Changing the query to use uppercase makes it pass tests, but for obvious reasons I'm not keen to flood the codebase with changes just for this.

```
SELECT * FROM foo INNER JOIN bar ON foo.id = bar.foo_id
```

I haven't dug through the code and grokked all the subtleties yet, happy to submit a pull request if you can give a little guidance on how you'd prefer it implemented.

**Comment by dsferruzza** [comment]
Hi!
Thanks for reporting!

Few months ago, I began to rewrite the module from scratch using parser combinators.
This v2 is almost done: https://github.com/dsferruzza/simpleSqlParser/tree/v2
It misses the condition parsing feature, but, except for that, it is quite stable.
The queries you wrote seem to work with v2.

I don't want to make big changes on v1, because it is a pain to maintain.
So you can wait or help me to get a stable v2, or make a PR on v1.
Of course I encourage you to try v2 and tell me if something is wrong!

**Comment by richmarr** [comment]
Thanks. The V2 branch works just fine with lower case SQL, so closing this one. V2 looks good!
